ReisikuludAutentimisega/ReisikuludAutentimisega/Models/Spending.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReisikuludAutentimisega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spending
    {
        public int Id { get; set; }
        public int TravelId { get; set; }
        public int TypeId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Document { get; set; }
    
        public virtual Travel Travel { get; set; }
        public virtual SpendingType SpendingType { get; set; }
        public virtual File File { get; set; }
    }
}

ReisikuludAutentimisega/ReisikuludAutentimisega/Models/SpendingType.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReisikuludAutentimisega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpendingType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpendingType()
        {
            this.Spendings = new HashSet<Spending>();
        }
    
        public int Id { get; set; }
        public string SpendingName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Spending> Spendings { get; set; }
    }
}

ReisikuludAutentimisega/ReisikuludAutentimisega/Controllers/SpendingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReisikuludAutentimisega.Models;
using System.IO;

namespace ReisikuludAutentimisega.Controllers
{
    public class SpendingsController : Controller
    {
        private WienerEntities1 db = new WienerEntities1();



        //public ActionResult File(HttpPostedFileBase file)
        //{
        //    if (file.ContentLength > 0)
        //        try
        //        {
        //            file.SaveAs(Path.Combine(Server.MapPath("~/..."), Path.GetFileName(file.FileName)));
        //            return File(file, "image/jpg");

        //        }

        //        catch
        //        {
        //            ViewBag.Message = "Faili ei lisatud";
        //        }



        //}

        private ActionResult File(HttpPostedFileBase file, string v)
        {
            throw new NotImplementedException();
        }



        // GET: Spendings
        public ActionResult Index()
        {
            var spendings = db.Spendings.Include(s => s.File).Include(s => s.Travel).Include(s => s.SpendingType);
            return View(spendings.ToList());
        }

        // GET: Spendings/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spending spending = db.Spendings.Find(id);
            if (spending == null)
            {
                return HttpNotFound();
            }
            return View(spending);
        }

        // GET: Spendings/Create
        public ActionResult Create(int TravelID)
        {


            ViewBag.Document = new SelectList(db.Files, "Id", "Filename");
            ViewBag.TravelId = new SelectList(db.Travels, "Id", "Id");
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName");
            
            return View(new Spending { TravelId = TravelID });
        }

        // POST: Spendings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TravelId,TypeId,Amount,Document")] Spending spending, HttpPostedFileBase file, ReportLog report)
        {
            if (ModelState.IsValid)
            {
                db.Spendings.Add(spending);                
                db.SaveChanges();
                int id1 = spending.Id;
                ReportLog.Log(report, $"New spending added: {id1}", Person.GetByEmail(User.Identity.Name).Id);
                if (file != null && file.ContentLength > 0)
                {
                    using (BinaryReader br = new BinaryReader(file.InputStream))
                    {
                        byte[] buff = br.ReadBytes(file.ContentLength);
                        Models.File mFile = new Models.File
                        {
                            Content = buff,
                            ContentType = file.ContentType,
                            Filename = file.FileName.Split('\\').LastOrDefault()??"no name"
                        };
                        db.Files.Add(mFile);
                        db.SaveChanges();

                        spending.Document = mFile.Id;
                        db.SaveChanges();
                    }
                }

                return RedirectToAction("Edit", "Travels", new { id = spending.TravelId });
            }

            ViewBag.Document = new SelectList(db.Files, "Id", "Filename", spending.Document);
            ViewBag.TravelId = new SelectList(db.Travels, "Id", "TravelName", spending.TravelId);
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName", spending.TypeId);
            return View(spending);
        }
        

        // GET: Spendings/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spending spending = db.Spendings.Find(id);
            if (spending == null)
            {
                return HttpNotFound();
            }
            ViewBag.Document = new SelectList(db.Files, "Id", "Filename", spending.Document);
            ViewBag.TravelId = new SelectList(db.Travels, "Id", "TravelName", spending.TravelId);
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName", spending.TypeId);
            return View(spending);
        }

        // POST: Spendings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TravelId,TypeId,Amount,Document")] Spending spending, ReportLog report)
        {
            if (ModelState.IsValid)
            {
                db.Entry(spending).State = EntityState.Modified;
                db.SaveChanges();
                int id1 = spending.Id;
                ReportLog.Log(report, $"Spending edited: {id1}", Person.GetByEmail(User.Identity.Name).Id);
                return RedirectToAction("Edit", "Travels", new { id = spending.TravelId });
            }
            ViewBag.Document = new SelectList(db.Files, "Id", "Filename", spending.Document);
            ViewBag.TravelId = new SelectList(db.Travels, "Id", "TravelName", spending.TravelId);
            ViewBag.TypeId = new SelectList(db.SpendingTypes, "Id", "SpendingName", spending.TypeId);
            return View(spending);
        }

        // GET: Spendings/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Spending spending = db.Spendings.Find(id);
            if (spending == null)
            {
                return HttpNotFound();
            }
            return View(spending);
        }

        // POST: Spendings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, ReportLog report)
        {
            Spending spending = db.Spendings.Find(id);
            db.Spendings.Remove(spending);
            db.SaveChanges();
            int id1 = spending.Id;
            ReportLog.Log(report, $"Spending deleted: {id1}", Person.GetByEmail(User.Identity.Name).Id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReisikuludAutentimisega/ReisikuludAutentimisega/Views/Spendings/Create.cshtml
@model ReisikuludAutentimisega.Models.Spending

@{
    ViewBag.Title = "Create";
}

<h2>Lisa uus kulu</h2>


@using (Html.BeginForm("Create", "Spendings", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TravelId, "Reisi ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TravelID", null, htmlAttributes: new { @class = "form-control", disabled = "disabled" })
                @Html.HiddenFor(model => model.TravelId)
                @Html.ValidationMessageFor(model => model.TravelId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeId, "Kulutüüp", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TypeId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, "Summa", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

         <label for="file">Lisa fail</label>
        <input type="file" name="file" id="file" />


        @*<div class="form-group">
            @Html.LabelFor(model => model.Document, "Document", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Document", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Document, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lisa fail" class="btn btn-default" style="width: 120px" />
                </div>
            </div>*@
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lisa uus kulu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Tagasi nimekirja", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReisikuludAutentimisega/ReisikuludAutentimisega/Views/Spendings/Delete.cshtml
@model ReisikuludAutentimisega.Models.Spending

@{
    ViewBag.Title = "Delete";
}

<h2>Kustuta reisikulu</h2>

<h3>Kas sa oled kindel, et soovid kirje kustutada?</h3>
<div>
   
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Summa
            @*@Html.DisplayNameFor(model => model.Amount)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            Kuludokument
            @*@Html.DisplayNameFor(model => model.File.Filename)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File.Filename)
        </dd>

        <dt>
            Reisi nimetus
            @*@Html.DisplayNameFor(model => model.Travel.TravelName)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Travel.TravelName)
        </dd>

        <dt>
            Kulutüüp
            @*@Html.DisplayNameFor(model => model.SpendingType.SpendingName)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpendingType.SpendingName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Kustuta" class="btn btn-default" /> |
            @*@Html.ActionLink("Tagasi nimekirja", "Index")*@
        </div>
    }
</div>

ReisikuludAutentimisega/ReisikuludAutentimisega/Views/Spendings/Details.cshtml
@model ReisikuludAutentimisega.Models.Spending

@{
    ViewBag.Title = "Details";
}

<h2>Reisikulude andmed</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Summa
            @*@Html.DisplayNameFor(model => model.Amount)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            Kuludokument
            @*@Html.DisplayNameFor(model => model.File.Filename)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.File.Filename)
        </dd>

        <dt>
            Reisi sihtkoht
            @*@Html.DisplayNameFor(model => model.Travel.TravelName)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Travel.TravelName)
        </dd>

        <dt>
            Kulutüüp
            @*@Html.DisplayNameFor(model => model.SpendingType.SpendingName)*@
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpendingType.SpendingName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Muuda", "Edit", new { id = Model.Id }) |
    @*@Html.ActionLink("Tagasi nimekirja", "Index")*@
</p>

ReisikuludAutentimisega/ReisikuludAutentimisega/Views/Spendings/Edit.cshtml
@model ReisikuludAutentimisega.Models.Spending

@{
    ViewBag.Title = "Edit";
}

<h2>Reisikulude muutmine</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.TravelId, "Reisi ID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TravelId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TravelId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TypeId, "Kulutüüp", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("TypeId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.TypeId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Amount,"Summa", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Document, "Kuludokument", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Document", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Document, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<img src="@Url.Action("Photo", new { id = Model.TravelPictures})" height="120" name="photo" id="photo" />
    <label for="file">Lae uus foto üles</label>
    <input type="file" name="file" id="file" />*@


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Salvesta" class="btn btn-default" />
        </div>
    </div>
</div>
}

@*<div>
    @Html.ActionLink("Tagasi nimekirja", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReisikuludAutentimisega/ReisikuludAutentimisega/Views/Spendings/Index.cshtml
@model IEnumerable<ReisikuludAutentimisega.Models.Spending>

@{
    ViewBag.Title = "Index";
}

<h2>Esitatud kulud</h2>

@*<p>
    @Html.ActionLink("Lisa uus kulu", "Create")
</p>*@
<table class="table">
    <tr>
        <th>
            Summa
            @*@Html.DisplayNameFor(model => model.Amount)*@
        </th>
        <th>
            Kuludokument
            @*@Html.DisplayNameFor(model => model.File.Filename)*@
        </th>
        <th>
            Reisi sihtkoht
            @*@Html.DisplayNameFor(model => model.Travel.TravelName)*@
        </th>
        <th>
            Kulutüüp
            @*@Html.DisplayNameFor(model => model.SpendingType.SpendingName)*@
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.File.Filename)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Travel.TravelName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SpendingType.SpendingName)
        </td>
        <td>
            @Html.ActionLink("Muuda", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Vaata", "Details", new { id=item.Id }) |
            @Html.ActionLink("Kustuta", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>